name: Build and Package Rootful

on:
  push:
    branches: [ rootful ]
  pull_request:
    branches: [ rootful ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Install ldid
        run: brew install ldid

      - name: Build .app with Xcode
        run: |
          xcodebuild -project varClean.xcodeproj \
                     -scheme varClean \
                     -configuration Release \
                     -sdk iphoneos \
                     -destination 'generic/platform=iOS' \
                     MARKETING_VERSION=$THEOS_PACKAGE_BASE_VERSION \
                     IPHONEOS_DEPLOYMENT_TARGET=14.0 \
                     CODE_SIGN_IDENTITY="" \
                     AD_HOC_CODE_SIGNING_ALLOWED=YES \
                     build

      - name: Locate .app File and Prepare for Packaging
        run: |
          mkdir -p Payload
          ROOT_HIDE_DIR=$(find /Users/runner/Library/Developer/Xcode/DerivedData/ -name 'varClean-*' -type d -print | head -n 1)
          APP_DIR="${ROOT_HIDE_DIR}/Build/Products/Release-iphoneos/varClean.app"
          cp -r "$APP_DIR" Payload/

      - name: Sign the .app with entitlements
        run: |
          ldid -S./entitlements.plist Payload/varClean.app/varClean

      - name: Re-package IPA after signing
        run: |
          zip -r9 varClean14.tipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: varClean14
          path: varClean14.tipa

      - name: Create Release and Upload IPA (Rootful)
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          files: varClean14.tipa
          tag_name: rootful
          name: Rootful Release ${{ github.run_number }}
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
