name: Build RHInject

on:
  push:
    branches:
      - "rhinject"
    paths-ignore:
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install Procursus
        uses: dhinakg/procursus-action@main
        with:
          packages: ldid findutils sed coreutils make dpkg

      - name: Install THEOS
        run: |
          set -x
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          mkdir -p "$THEOS"
          curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos >> install-theos.sh
          gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos.sh
          bash install-theos.sh
          curl -L https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz --output "$THEOS/sdks/iPhoneOS16.5.sdk.tar.xz"
          xz -d "$THEOS/sdks/iPhoneOS16.5.sdk.tar.xz"
          tar -xf "$THEOS/sdks/iPhoneOS16.5.sdk.tar" -C "$THEOS/sdks"
          rm "$THEOS/sdks/iPhoneOS16.5.sdk.tar"

      - name: Build Package
        run: |
          set -x
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          gmake package FINALPACKAGE=1
          DEB_PATH=$(find packages -maxdepth 1 -name '*.deb' | head -n 1)
          test -n "$DEB_PATH"
          echo "deb_path=${DEB_PATH}" >> "$GITHUB_ENV"
          echo "deb_name=$(basename "$DEB_PATH")" >> "$GITHUB_ENV"

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: rhinject
          release_name: RHInject
          body: Automatically updated RHInject standalone builds.
          draft: false
          prerelease: false
          overwrite: true
          files: ${{ github.workspace }}/${{ env.deb_path }}
